name: Demo to merge PR automatically

on:
  push:
    branches:
      - main

jobs:
  updateAuthor:
    runs-on: windows-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Merge Pull request1
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.demo-1.outputs.pull-request-number }}
          method: squash
